### ISSUE TITLE
Using the preprocessor

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#101]
Is it possible to specify the preprocessor flags in the fobis file? When I add:

```
preproc = /fpp
```
it doesn't work. 

The command-line flag `--preproc /fpp` does work. However one odd thing is that in the debug print output it seems to be adding it twice:
```
    Vendor: "intel"
    Compiler command: "ifort"
    Module directory switch: "/module:"
    Compiling flags: "-c -standard-semantics -O2 /fpp /fpp"
    Linking flags: ""
    Preprocessing flags: "/fpp /fpp"
    Coverage: False
    Profile: False
```
It does compile though. But, I'm wondering how to add it to the fobis file.

(Note: I'm trying this on Windows so that might make a difference)

**Comment by szaghi** [comment]
Hi Jacob,

happy to read you again. I really do not remember if I added a way to specify a preprocessor. Later today I'll check. I am sorry, but last year has been a nightmare (concerning work), the time for FOSS was near to zero.

**Comment by szaghi** [comment]
@jacobwilliams Dear Jacob, I think you are no more interest into FoBiS, but it should be able now to specify the pre-preprocessor.

I am going to closing this, but feel free to re-open it or a new one if necessary.

Cheers

P.S. I hope you are fine, probably I will have more time in time the future for Fortran programming again
