### ISSUE TITLE
encoding error with Python3.6 (depending on the building env) when building `forbear`

### ISSUE THREAD

**Issue by d-vanzo** [szaghi/FoBiS#106]
Dear @szaghi , thank you for your useful tools!
I am trying to test the building of your `forbear` library using both Python2.X and Python3.X.
I tested 3 configurations, all based on Linux-Ubuntu18.04 system:

1. Python2.X clean and protected building env (docker) --> all fine
2. Python2.X  in my local "dirty" WS --> all fine
3. Python3.X  in my local "dirty" WS --> all fine
4. Python3.X clean and protected building env (docker) --> **encoding error**

~~~bash
Traceback (most recent call last):
  File "/usr/local/bin/FoBiS.py", line 21, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/fobis/fobis.py", line 45, in main
    run_fobis()
  File "/usr/local/lib/python3.6/dist-packages/fobis/fobis.py", line 71, in run_fobis
    run_fobis_build(configuration)
  File "/usr/local/lib/python3.6/dist-packages/fobis/fobis.py", line 88, in run_fobis_build
    pfiles = parse_files(configuration=configuration)
  File "/usr/local/lib/python3.6/dist-packages/fobis/fobis.py", line 264, in parse_files
    pfile.parse(inc=configuration.cliargs.inc)
  File "/usr/local/lib/python3.6/dist-packages/fobis/ParsedFile.py", line 295, in parse
    for line in ffile:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5034: ordinal not in range(128)
~~~

Given that case 3 works fine... I guess I have some python module or env vars or... something else that make it works. Case 4 (clean and minimal python3 env) is not.
Do you ever encounter this issue? Any suggestion on a python module that can fix the problem?
I can share the Dockerfile I am using in case.
Thanks!

**Comment by jacobwilliams** [comment]
https://pythonclock.org/  😄

**Comment by d-vanzo** [comment]
Hi @szaghi 
issue fixed (I guess). It was related  to the default system encoding, that in the docker container is apparently not set by default.
Long story short, if I define the locales in the Dockerfile

~~~bash
# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
~~~
then FoBiS (Python3) works in the docker container. Not sure that this is the most elegant solution, but seems to work.
Cheers

**Comment by szaghi** [comment]
Wow, thank you very much @d-vanzo I definitively have to keep this is mind.

Cheers
