### ISSUE TITLE
Windows compatible encoding

### ISSUE THREAD

**Issue by Diftin** [szaghi/FoBiS#109]
I discovered that under Windows 10, I can't use fobis to compile forbear due to encoding issues. The following changes solved the issue:

In the source file ParsedFile.py
line 294:
- old:  `ffile = open(self.name, "r")`
- new: `ffile = open(self.name, "r", encoding="utf8")`

lines 333 and 335:
- old:  `source = str(open(self.name, 'r').read())`
- new: `source = str(open(self.name, 'r', encoding="utf8").read())`

I suppose you would have to specify the encoding for all lines where you open a file in order to make it work all the time, but this did the job for me.

**Comment by szaghi** [comment]
Hi @Diftin 

thank you for the advice. Can you arrange a pull request? I'll be happy to integrate this patch.

**Comment by Diftin** [comment]
Hi @szaghi 

Yes I can do this later. However, I was not sure whether the encoding should be specified everywhere or not.. for me it works with only these 3 changes. 

Thanks for your work.

**Comment by szaghi** [comment]
this a *start* :-)

I have not access to a MS Windows system, thus for me it is really difficult to test patches for that OS. If your patches work on my GNU Linux boxes, I'll be happy to accept them *blindly*.

**Comment by Diftin** [comment]
Hi @szaghi ,
I saw that my pull request did not pass your tests. However, I didn't understand what went wrong in the error messages. Do you have an idea what went wrong?

Thanks,
Fabian

**Comment by szaghi** [comment]
Hi @Diftin 

I saw, but I have not yet found the time to check, I hope to do it in this week.

**Comment by szaghi** [comment]
Hi @Diftin 

sorry for my delay, I hope to check it soon, my apologize.

**Comment by Diftin** [comment]
The issue seems to be back compatibility to Python 2. I now have a solution which bypasses this problem, but only solves my issue in Python 3 (which is sufficient for me). I will make another pull request with this solution.

**Comment by Diftin** [comment]
Hi @szaghi,
The code in the pull request seems to work as intended, but still somehow fails at the very end..

**Comment by szaghi** [comment]
Hi, I am out of office for my holidays, I'll return at the end of August, sorry

**Comment by Diftin** [comment]
Hi @szaghi, any news about integrating the small patch for my windows issue?

**Comment by szaghi** [comment]
@Diftin 

I am very sorry for my delay.

Have you seen the pull request of @d-vanzo ? it is could be a fix. I am going to merge his pull request, after can you test the new merged-version?

**Comment by Diftin** [comment]
Yes, it is the same pull request with the "import sys" at the beginning, which seemed to be the reason for the failed unittest of my pull request. So my pull request is not needed anymore.

**Comment by szaghi** [comment]
@Diftin oh, thanks, I am sorry to have not found the time for reviewing your pull request, my bad

**Comment by szaghi** [comment]
@Diftin Is this now fixed?

**Comment by Diftin** [comment]
Yes, thanks.
