### ISSUE TITLE
Build not working on multiple PCs

### ISSUE THREAD

**Issue by theinlinaung2010** [szaghi/FoBiS#114]
I use FoBiS script "fobis.py build" to compile my Fortran project with gnu fortran compiler. Below are the contents of my fobos file.
`
[default]

$DEBUG_GNU   = -O0 -g3 
$CSTATIC_GNU = -cpp -c -frealloc-lhs 

compiler     = gnu
cflags       = $CSTATIC_GNU $DEBUG_GNU
lflags       = $DEBUG_GNU
mod_dir      = ./mod/
obj_dir      = ./obj/
exclude_dirs = ./exclude/
target       = main.f90
output       = main.exe
colors       = True
quiet        = True
log          = True
`
Although I can successfully build and run the project on my windows PC, it produced undefined reference errors when I tried to build it on my laptop. The file paths in the build error messages referred to the locations in the PC. Since I use a different username for the laptop, the paths are different. I had to clean the build and rebuild again even though previously compiled executable runs fine on my laptop.

**Comment by szaghi** [comment]
Hi @theinlinaung2010 

sorry for my delay, but last months were very complicated for me. Are you still facing with this issue, can I help in some way?

**Comment by theinlinaung2010** [comment]
@szaghi thank you for the reply.

I somehow managed to get it working on both computers. I don't exactly remember what I did (maybe a clean reinstall of fobis). So I think there is no issue for now.

**Comment by szaghi** [comment]
@theinlinaung2010 great, happy you solved the problem.

Cheers
