### ISSUE TITLE
Failing to find correct dependency

### ISSUE THREAD

**Issue by ShatrovOA** [szaghi/FoBiS#115]
Dear @szaghi 

I think I found bug in building dependency structure of a project. This happens when declaring module as
```fortran
use :: parent_module
```
instead of
```fortran
use parent_module
```

For example [this](https://github.com/wavebitscientific/datetime-fortran) project can't be build with FoBiS:
```bash
FoBiS.py build -t src/lib/datetime.f90 -mklib static
...
Building ./src/lib/datetime.f90
Compiling ./src/lib/mod_datetime.f90 ./src/lib/mod_timedelta.f90 ./src/lib/mod_clock.f90 ./src/lib/mod_strftime.f90 serially
./src/lib/mod_datetime.f90:13:6:

   13 | use :: mod_timedelta,only:timedelta
      |      1
Fatal Error: Cannot open module file 'mod_timedelta.mod' for reading at (1): No such file or directory
compilation terminated.

./src/lib/mod_clock.f90:10:6:

   10 | use :: mod_datetime,only:datetime
      |      1
Fatal Error: Cannot open module file 'mod_datetime.mod' for reading at (1): No such file or directory
compilation terminated.

./src/lib/mod_datetime.f90:13:6:

   13 | use :: mod_timedelta,only:timedelta
      |      1
Fatal Error: Cannot open module file 'mod_timedelta.mod' for reading at (1): No such file or directory
compilation terminated.
./src/lib/mod_clock.f90:10:6:

   10 | use :: mod_datetime,only:datetime
      |      1
Fatal Error: Cannot open module file 'mod_datetime.mod' for reading at (1): No such file or directory
compilation terminated.
```

But when you remove '::' in files
- mod_clock: lines 10,11
- mod_datetime: lines 13, 14, 15

everything is ok.

Best regards!

**Comment by szaghi** [comment]
@ShatrovOA 

Thank you very much!

I'll try to fix it very soon.

Cheers

**Comment by szaghi** [comment]
@ShatrovOA 

In the new version 3.0.2 there is a fix, let me know if this works.

Thank you again, 

cheers

**Comment by ShatrovOA** [comment]
Everything works for me now.

Once again, thank you!

**Comment by szaghi** [comment]
@ShatrovOA thank you for reporting the bug, it is really appreciated.

I am closing the issue, but feel free to re-open if further usage shows that the fix is not enough.

Cheers.
