### ISSUE TITLE
Add future module as PyPi dependency

### ISSUE THREAD

**Issue by AnnanFay** [szaghi/FoBiS#117]
https://github.com/szaghi/FoBiS/blob/6856038b310645f1cb49d02b419daa4cb47901ec/src/main/python/fobis/Colors.py#L27

This line is causing issues after installing from PyPI. `future` isn't a built in module and is not listed in `setup.py`.

**Comment by szaghi** [comment]
Dear @AnnanFay 

Thank you very much for the bug alert, I am sorry for the delay, but I am out of office for my holidays.

As soon as possible I'll try to fix it.

Regards

**Comment by jubilee2** [comment]
i have same issue i tested need following 2 packages [future, configparser]

i use this command to temporary way to fix issue
```
pip install FoBiS.py future configparser
```

**Comment by szaghi** [comment]
Dear @AnnanFay @jubilee2 

I have just uploaded a new version (v3.0.3): the setup.py now contains the *[ "multiprocessing", "future", "configparser" ]* dependencies, I hope this fix this bug.

I'll look forward for your feedback for closing this issue.

Thank you again for the alert.

Cheers

**Comment by phdru** [comment]
The "fix" introduced new bug: the package cannot be installed with Python 3 now. See https://stackoverflow.com/q/63686642/7976758.

**Comment by jubilee2** [comment]
@szaghi 
new version can install in python2 but not work on python3
like multiprocessing is work on python2 only

**Comment by szaghi** [comment]
@phdru @jubilee2 

I have just merged the PR for fixing the multiprocessing issue, let me know if v3.0.4 fix the bug.

Thank you, cheers

**Comment by jubilee2** [comment]
> The "fix" introduced new bug: the package cannot be installed with Python 3 now. See https://stackoverflow.com/q/63686642/7976758.

Thank you very much!

**Comment by szaghi** [comment]
@jubilee2 thanks

just uploaded v3.0.5 with your fixed testing script

**Comment by AnnanFay** [comment]
I can't fully test this at the moment but looks good.

`colorama` also seems like a required module on windows? https://github.com/szaghi/FoBiS/blob/f6cb26beef198269bf4413247a9183b86a2aae6a/src/main/python/FoBiS.py#L24

Something [like this may work](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies) (untested):
```python
    install_requires=[
        "future",
        "configparser",
        "colorama ; platform_system=='Windows'"
    ]
```

**Comment by szaghi** [comment]
@AnnanFay thank you very much for the allert, @jubilee2 has just created a PR to fix this, thak you both.

I have not the possibility to test it on Windows, I hope it works.

I am going to close this issue, but feel free to reopen it if there are new issues related to it.

Cheers
