### ISSUE TITLE
fobos local variables

### ISSUE THREAD

**Issue by szaghi** [szaghi/FoBiS#20]
Add feature: allow definition of local variables inside fobos file that can be shared between different modes/options

**Comment by Tobychev** [comment]
Thank you! I'm sure this will be useful for me :)

**Comment by szaghi** [comment]
@myself: remember to document this feature!

**Comment by Tobychev** [comment]
Hello Stefano, 
today I realised I could use this feature! So now I'm here to remind you to document it in the wiki ;)

**Comment by szaghi** [comment]
:-) Good job!

I am doing it now...

**Comment by szaghi** [comment]
Dear Tomas,

these are for you: 

+ https://github.com/szaghi/FoBiS/wiki/fobos-modes-templates
+ https://github.com/szaghi/FoBiS/wiki/fobos-modes-variables

I am sorry for my bad English... I hope they are clear enough.

Let me know how you will use them... :-)

See you soon.
