### ISSUE TITLE
Non-module source files

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#22]
Can FoBiS handle old style .f Fortran files that are just subroutines or functions (not modules)?  There could be a flag where you pass in the file names or directories and tell it to compile them even though they are not part of the set of files that were analyzed for module dependency.  In this case, the order is not important.

**Comment by szaghi** [comment]
It should already be implemented. FoBiS.py should be able to recognize
non-module files containing procedures and it compiles them just without
any hierarchy, then pass the compiled objects to the linker. Do you have
any problems with this?

P.S. I am working on the other issue, but it is not so trivial...

Il giorno 20:34 ven 09/gen/2015 Jacob Williams <notifications@github.com>
ha scritto:

**Comment by jacobwilliams** [comment]
Terrific!  I asked the question before I tried to test it.  Will let you know if I have any problems.

**Comment by szaghi** [comment]
Do not warry, I do this often :-)

I leave this issue open for any case...
