### ISSUE TITLE
Define file extension to be preprocessed

### ISSUE THREAD

**Issue by hct0r** [szaghi/FoBiS#24]
Hi Guys,

Is there a way to define the file extensions that will be preprocessed?
That way only the files with those extensions will be passed to PreForM and located into the PreForM folder.
And the files not preprocessed will be compiled normally.

for example only the files with extension `*.pf ` and `*.ph` will be preprocessed and converted into `*.f` and `*.h` files and copied into the `pfm_dir` folder

If the selection cannot be done based on file's extension, could it be file name based?
The idea would be not to preprocess all files.

Thank you

**Comment by szaghi** [comment]
Presently not, but I can implement this feature quickly. Later in the
morning I will push the new version. See you soon.
Il 03/feb/2015 22:14 "hct0r" <notifications@github.com> ha scritto:

**Comment by szaghi** [comment]
Hi hct0r,

I have just pushed the new version. I have documented the new features [here](https://github.com/szaghi/FoBiS/wiki/Taste).

I have also added your nickname to the contributors [list](https://github.com/szaghi/FoBiS/wiki/About).

Thank you for trying FoBiS.py.

See you soon.
