### ISSUE TITLE
Python 3 issue

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#25]
There seems to be an issue when using FoBiS with Python 3.4.2.  

````Python
Traceback (most recent call last):
  File "./FoBiS.py", line 1129, in <module>
    __builder__.build(file_to_build=pfile,output=__cliargs__.output,nomodlibs=__nomodlibs__,mklib=__cliargs__.mklib)
  File "./FoBiS.py", line 399, in build
    print(self.colors.red+result[1]+self.colors.end)
TypeError: Can't convert 'bytes' object to str implicitly
````
I get this when using the ```-libs``` flag with a library that doesn't exist.

**Comment by szaghi** [comment]
You are right. I have not yet tested with python 3.x... I will try to
support this later, after the PyPi publishing. See you soon.
Il 05/feb/2015 01:51 "Jacob Williams" <notifications@github.com> ha scritto:

**Comment by szaghi** [comment]
Hi Jacob, 

the new version 1.2.8 (on both Github and PyPi) should support also Python 3.4.x.

Let me known if you have any problems. I close this for the moment, but I will reopen it as soon as bugs will be found.

See you soon.
