### ISSUE TITLE
Library search path

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#26]
Might be nice if FoBoS supported the gfortran ```-L``` flag for the library search path.  I think currently, you have to include the full path to the libraries used with the ```-libs``` flag, since gfortran doesn't use the include directory when searching for libraries.

**Comment by szaghi** [comment]
You are rigth. I try to implement it late in the morning, maybe together
the publishing on PyPi. See you soon.

**Comment by szaghi** [comment]
Hi Jacob,

I am trying to implement this feature, but I am failing building a working example (I always link libraries with full path). Can you provide examples of commands for liking with -L(-l)? Both GNU gfotran and Intel ifort seem to support the same syntax. For example, let us assume the following setup:

```bash
├── build
│   ├── mod
│   └── obj
│       └── cumbersome.o
├── fobos
├── precompiled
│   ├── mod
│   │   └── nested_1.mod
│   └── obj
│       └── first_dep.o
├── README.md
└── src
    └── cumbersome.f90
```
Which commad I should use to build without the full path `precompiled/obj/first_dep.o`?

With both gfortran and ifort I have tried:

```bash
ifort build/obj/cumbersome.o -Lprecompiled/obj first_dep.o -o build/Cumbersome
```
but I have failed
```bash
ifort: error #10236: File not found:  'first_dep.o'
```

**Comment by jacobwilliams** [comment]
I think it only works for libraries (not ```.o``` files).  Here's an example (with gfortran...but I think ifort might be the same).

````
├── build
├── lib
│   └── libblah.a
└── src
    └── cumbersome.f90
````

To compile, you would use:

```
gfortran -lblah -L./lib ./src/cumbersome.f90 -o build/Cumbersome
```
Note that the library is named ```libblah.a```, but you only use ```-lblah``` in the call (the compiler puts the ```lib``` prefix and ```.a``` suffix.  This is weird but that's what it does.

**Comment by szaghi** [comment]
Thanks, I will try it monday.

Have a good weekend.

**Comment by szaghi** [comment]
Dear Jacob,

your feature should be implemented. I have pushed the new release on both this github repo and PyPi, thus you can install via `pip` or manually.

I have added some more documentations:

+ https://github.com/szaghi/FoBiS/wiki/ChangeLog
+ https://github.com/szaghi/FoBiS/wiki/Linking-external-libraries
+ https://github.com/szaghi/FoBiS/tree/master/examples/cumbersome_dependency_program_precompiled
+ https://github.com/szaghi/FoBiS/tree/master/examples/cumbersome_dependency_program_external_libs

Please, let me know of any bugs you will find.

P.S. Now that FoBiS.py is on PyPi I am testing some nice (IMHO) Travis CI "extensions" for Fortran programs... maybe you will interested on that.
