### ISSUE TITLE
Idea: Recompile if -cflags have changed

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#28]
It would be interesting if FoBiS could detect if you have changed the ```-cflags``` since the last time you compiled, and then realize that it needs to recompile everything again.  This could be a useful feature.

**Comment by szaghi** [comment]
very nice idea. I will try it later in the morning. Thank you.

**Comment by szaghi** [comment]
Dear Jacob,

this is for you https://github.com/szaghi/FoBiS/wiki/Autorebuild-when-compiling-flags-change

It is into the new version 1.2.9 that can be installed manually or from PyPi. It contains also the bug fix on linking library projects.

Let me know of any bugs you find.

See you soon.
