### ISSUE TITLE
pip install with Python3

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#30]
```pip install FoBiS.py``` doesn't work for Python 3.  It seems to be trying to install the Python 2 version of the "multiprocessing" package?  The error I get is:
```bash
C:\Users\USERNAME>pip install FoBiS.py
Downloading/unpacking FoBiS.py
  Downloading FoBiS.py-1.2.9.tar.gz
  Running setup.py (path:C:\Users\USERNAME\AppData\Local\Temp\pip_build_USERNAME
\FoBiS.py\setup.py) egg_info for package FoBiS.py

Downloading/unpacking multiprocessing (from FoBiS.py)
  Running setup.py (path:C:\Users\USERNAME\AppData\Local\Temp\pip_build_USERNAME
\multiprocessing\setup.py) egg_info for package multiprocessing
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\USERNAME\AppData\Local\Temp\pip_build_USERNAME\multiprocess
ing\setup.py", line 94
        print 'Macros:'
                      ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\USERNAME\AppData\Local\Temp\pip_build_USERNAME\multiprocessing\
setup.py", line 94

    print 'Macros:'

                  ^

SyntaxError: invalid syntax

----------------------------------------
```
This is using the Anaconda 3-2.1.0 Python package on Windows (don't know if that makes a difference or not).

**Comment by szaghi** [comment]
Interesting, I will check this late in the morning. Thanks

Il giorno 00:03 mer 11/feb/2015 Jacob Williams <notifications@github.com>
ha scritto:

**Comment by szaghi** [comment]
Opsss, it seems that multiprocessing module is into the standard modules library since 2.6+. I am now removing it has dependency from PyPi installer.

Thank you for testing it.

**Comment by szaghi** [comment]
Hi Jacob,

the new version (1.3.0) should be multiprocessing-bug free!

Presently, Travis CI fails to build FoBiS.py: I have introduced unit tests for auto-checking purposes that work on my box, but fail on Travis. I am investigating this issue, but it should be irrelevant for the end-user.

See you soon.

**Comment by fontran** [comment]
Sorry but has this issue been fixed with the latest Anaconda3-2.1.0-Windows-x86_64.exe?

Thanks

**Comment by ryanjdillon** [comment]
I am getting the same issue.

`Python 3.5.2`
`pip 8.1.2`

The package it is grabbing is `multiprocessing-2.6.2.1.tar.gz`

**Comment by ryanjdillon** [comment]
My apologies, it looks like this is now just a [backport](https://pypi.python.org/pypi/multiprocessing/).

**Comment by szaghi** [comment]
So all is ok?

**Comment by ryanjdillon** [comment]
Yes, my VIM plugin led me to believe the standard library `multiprocessing` module didn't have the `Event` class, which led me to attempt `pip3` installing this. 

All is okay, but would be great if this didn't come up as an available package for Python 3 in pip.
