### ISSUE TITLE
improve compiler command check

### ISSUE THREAD

**Issue by szaghi** [szaghi/FoBiS#32]
The supported compiler have default compiler command (gfortran, ifort, g95...) that must be more accurately checked, e.g. in many OS gfortran is installed as gfortran-4.x.  This can cause problems.

**Comment by jacobwilliams** [comment]
One way to do it is to allow for the option of directly specifying the compiler command to run (so, ```gfortran``` or ```gfortran-4.9```, rather than ```gnu```).

**Comment by szaghi** [comment]
Yes, this is an option, but:

+ `gnu` indicates the compiler vendor, not the compiler command; this means that `gnu` indicates many other setting rather than only the compiler command (namely `gfortran`);
+ in case `mpi` is used the compiler command will not start with `gfortran`, but it is (typically) `mpif90`;

Thus if the compiler specification includes also the compiler command the mpi case becomes cumbersome. On the other hand, what you have suggested can be already done: you can select `gnu` as the compiler vendor (thus all the GNU gfortran defaults settings are used) and you can specify **also** the compiler command, e.g. `fc = gfortran-4.9`, to override the compiler command default (`fc = gfortran`).  Besides, you can also overcome this by means of the fully custom compiler where you must specify all settings (and thus also the compiler command).

Anyhow, the above are only dirty workarounds: I am now searching for a more *clean* solution that allows FoBiS.py to **automatically** detect the compiler command(s) available for the supported compiler vendors. In case of the GNU gfortran FoBiS.py should be able to find all the **serial** compiler commands (e.g. `gfortran`, `gfortran-4.x`, `gfortran-5.x`...) and (maybe) select be default the latest version available). This problem is present also for IBM XL Fortran compiler where typically you have xlf90, xlf95... compiler commands. Moreover, it is even more complicated to detect the compiler command when mpi is used (in my workflow, I commonly recompile OpenMPI/MPICH with my compilers and the compiler command is always `mpif90`, but this is only my way... others can rename the compiler commands with their own names).

As consequence, I am not agree to substitute `gnu` with the actual compiler command `gfortran-xxx`, but thank you very much for your suggestion. If you have other solutiosn that can help me to address the above issues, please let me know!

See you soon.

**Comment by Tobychev** [comment]
I think the task of keeping track of the compiler versions installed on a particular machine is best left to the system administrator, FoBiS using a single name and leaving it to the user to for example create links to the correct binary.

This solution does imply two things to work really well: that the user can set the default name used, and that FoBiS reports the exact version of the compiler being used when compiling.

**Comment by szaghi** [comment]
Hi Tomas,

interesting point!

Presently, FoBiS.py allows the user to set the compiler command, e.g. you can set `compiler=gnu` thus all general settings of gfortran are done, and then set `fc=gfortran-4.9`, but the actual version is not reported, just the command the user set! It is simply to show also the actual version...

So you think that it is not a good idea to try to check the latest compiler version available for those supported... Ok, this is actually placed into the freezer :-)

Thank you again,

see you soon.
