### ISSUE TITLE
Cleaning issue

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#36]
If I want to put the obj and mod code in the build directory (not in a subdirectory), it seems to work using ```-dmod ./ -dobj ./```.  However, if I try to clean this, I get an error.
Command:
```bash
FoBiS.py clean -dmod ./ -dobj ./ -dbld ./lib/
```
Error is:
```Python
OSError: [Errno 22] Invalid argument: 'lib/./'
```

**Comment by szaghi** [comment]
Thank you. The paths must be sanitized... later in the morning i will try
to fix them

Il giorno 21:15 dom 15/feb/2015 Jacob Williams <notifications@github.com>
ha scritto:

**Comment by szaghi** [comment]
Hi Jacob,

I have pushed a new commit (not yet into PyPi), that should have fixed this bug. The API is fully backward, but now the directory eventually defined for mods and objs are not removed, just their contents. In particular the cleaner now does: for each file into `mod_dir` with .mod extension and for each file into `obj_dir` with .o extension the cleaner does a `file_remove` but the directories are untouched. In your scenario (where you place all outputs into the same directory) the present behavior and the old one should be identical (all the mods and objs are removed), but in my typical workflow it does not... I am advised :-)

A soon as I address all your other issues I will publish new version on PyPi.

See you soon.

P.S. if you FoBiS.py new README you should recognize a badges arrangement inspired by your... thank you very much!

**Comment by szaghi** [comment]
The new release 1.3.2 on both PyPi and github should be free of this bug.

See you soon.
