### ISSUE TITLE
Feature request: better/more verbose output

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#39]
It would be nice if there was a flag to increase the verbosity of FoBiS.py to help trouble shoot problems. There should be a flag that makes FoBiS.py output what commands it is running as it runs them. Right now, when something goes wrong it is too opaque as to whether the problem was in FoBiS.py (a bug) or if the user did something wrong. For example, see https://github.com/jacobwilliams/json-fortran/issues/53 where the problem was an extra space was introduced into the build script. If there had been some sort of step by step debugging output it would have been easier to see that flags weren’t passed into FoBiS.py due to an error in the shell script.

**Comment by szaghi** [comment]
Hi Izaak,

Indeed there is yet the `quiet` option for making outputs more or less verbose. I think your request is more likely a `debug` mode rather than a verbose mode, do you agree? Anyhow tomorrow you will have the outputs with each command executed.

Thank you very much for your help

**Comment by zbeekman** [comment]
Sure, calling it debug or verbose… either are fine.

As far as the quiet option… it seems that there is only the ability to *decrease* verbosity using quiet, not *increase* it, as per the documentation here: https://github.com/szaghi/FoBiS/wiki/Getting-Started

**Comment by szaghi** [comment]
Hi Izaak,

you feature request should be added to the new v1.5.2 just uploaded on both github and PyPi.

I have added you as contributor (https://github.com/szaghi/FoBiS/wiki/About#contributors), I hope you do not dislike this.

See you soon.

**Comment by zbeekman** [comment]
Thanks for the update! I don’t mind at all being listed as a contributor. Sorry I haven’t had a chance to look at #38… it sounds like it could be the arg_parse quote bug you mentioned… I’ll send you a link to my branch of json-fortran where I’m seeing the error once it’s in slightly better shape and also test all the versions of FoBiS.py to figure out which introduced the error.

**Comment by szaghi** [comment]
Don't worry for the #38. I leave it open just as a remainder. If in the next future I will not have any feedback about it I will close.

Thank you very much for your help.

See you soon.

**Comment by zbeekman** [comment]
Hi @szaghi I can’t figure out how to get the debug/verbose output to work… Right now I can’t build a relatively simple project and can’t figure out why…

**Comment by szaghi** [comment]
Should be -verbose
