### ISSUE TITLE
pypandoc

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#42]
When I try to update FoBiS.py using ```sudo pip install FoBiS.py --upgrade```, I get the error:

```Python
  File "<string>", line 17, in <module>

  File "/private/tmp/pip_build_root/FoBiS.py/setup.py", line 3, in <module>

    import pypandoc

ImportError: No module named pypandoc
```

**Comment by zbeekman** [comment]
Me too

**Comment by szaghi** [comment]
Yes, i see last night. It is is only a missing dependency on .travis.yml : i forget to ad pipi install pypandoc! Unlucky i cannot fix this before monday. the previous version has not this broken travis

**Comment by szaghi** [comment]
Fixed.
