### ISSUE TITLE
heritage flags switch causes FoBiS.py to fail if output directories missing

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#45]
See the log here: https://travis-ci.org/zbeekman/json-fortran/jobs/53563827

FoBiS.py will happily create a new directory to put compiled programs and libraries in, BUT this directory is also where the .cflags.heritage file is stored. When compiling with -ch turned on, FoBiS.py should be able to treat this case of a missing directory and .cflags.heritage file as if the .cflags.heritage file had been deleted.

This is the error I see:
```
File "/usr/local/bin/FoBiS.py", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/fobis/fobis.py", line 14, in main
    __config__.run_fobis()
  File "/usr/local/lib/python2.7/dist-packages/fobis/config.py", line 466, in run_fobis
    self._get_cli(fake_args=fake_args)
  File "/usr/local/lib/python2.7/dist-packages/fobis/config.py", line 436, in _get_cli
    self._postinit()
  File "/usr/local/lib/python2.7/dist-packages/fobis/config.py", line 130, in _postinit
    self._check_cflags_heritage()
  File "/usr/local/lib/python2.7/dist-packages/fobis/config.py", line 119, in _check_cflags_heritage
    with open(self.cliargs.build_dir + '.cflags.heritage', 'w') as chf:
IOError: [Errno 2] No such file or directory: ‘lib/.cflags.heritage’
```

**Comment by szaghi** [comment]
Hi Izaak, you are right. This is a known bug that I have already fixed on my testing branch. I have not yet uploaded it because I would like to finish the gcov parser (almost finished!).

Tomorrow I will upload the new version. Thank you Izaak.

**Comment by zbeekman** [comment]
no rush, happy to hear that a fix is in the works! Thanks so much!

**Comment by szaghi** [comment]
This should be fixed in the new version uploaded.

**Comment by zbeekman** [comment]
just tested it, and it works like a charm, thanks so much!

**Comment by szaghi** [comment]
I am happy, anyhow... there is bug (not related to this issue, just my OCD unittests...)! 

With python 3.x I have problems in converting byte string to string... I am trying to fix it.
