### ISSUE TITLE
Makefile export

### ISSUE THREAD

**Issue by zmiimz** [szaghi/FoBiS#49]
It seems that the function save_makefile which I am mostly interested in, has not been invoked in the source code and export to Makefile doesn't work

**Comment by szaghi** [comment]
Opss.... In a previous code refactoring it should be stripped out! I try fix it immediately.

**Comment by szaghi** [comment]
@zmiimz 

I have just pushed new a release (1.6.1) on both PyPi and Github that should be free from this bug.

I am closing this issue, but feel free to reopen it if the issue still persists.

Thank you very much for using FoBiS.py.

See you soon.

**Comment by szaghi** [comment]
@zmiimz 

Have you tried the makefile produced by the new version? I have found a test case for which it seems that the makefile generated fails, but I am not completely sure it is a bug of FoBiS.py. If you find any issues on the generated makefiles, please let me know.

See you soon.

**Comment by zmiimz** [comment]
Yes, it works. Thank you.  I will continue to test it on my small projects.
