### ISSUE TITLE
FoBis.py -h command

### ISSUE THREAD

**Issue by zmiimz** [szaghi/FoBiS#50]
There should be some note about  additional help from 
FoBiS.py build -h
FoBiS.py clean -h
FoBiS.py rule -h
commands  in the FoBis.py -h output because it is not fully obvious/intuitive that they exist?

**Comment by szaghi** [comment]
Hi zmiimz,

thank you for your suggestion. Indeed, I follow the standard `argparse` usage, but I agree that for the end-user (with experience with Python *argparse* module) it is not so clear. I will try to improve the CLI help as soon as possible.

See you soon.

**Comment by szaghi** [comment]
Hi zmiimz,

I have just uploaded a new version into which (I hope) I have added a more clear help message. It should like as:
```bash
usage: FoBiS.py [-h] [-v] {rule,build,clean} ...

a Fortran Building System for poor men

optional arguments:
  -h, --help          show this help message and exit
  -v, --version       Show version

Commands:
  Valid commands

  {rule,build,clean}
    build             Build all programs found or specific target(s)
    clean             Clean project: remove all OBJs and MODs files... use
                      carefully
    rule              Execute special rules or user's ones defined into a
                      fobos file

For more detailed commands help use
  FoBiS.py build -h,--help
  FoBiS.py clean -h,--help
  FoBiS.py rule -h,--help
```

Does it look more clear now?

I have also added you into the contributors list: https://github.com/szaghi/FoBiS/wiki/About#contributors

I am closing this issue, but if you do not like the new help message reopen the issue and let me know how to improve it.

Thank you for using FoBiS.py.

See you soon.

**Comment by zmiimz** [comment]
yes, indeed.  
thank you.
