### ISSUE TITLE
UnicodeDecodeError?

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#53]
I'm seeing some sort of bug maybe. See below. Interestingly, if I run FoBiS again, the error goes away.

```python
Compiling src/json_module.F90 serially
Traceback (most recent call last):
  File "/Users/anaconda/bin/FoBiS.py", line 5, in <module>
    main()
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/fobis.py", line 14, in main
    __config__.run_fobis()
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/config.py", line 638, in run_fobis
    self._build()
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/config.py", line 536, in _build
    builder.build(file_to_build=pfile, output=self.cliargs.output, nomodlibs=nomodlibs, mklib=self.cliargs.mklib, verbose=self.cliargs.verbose, log=self.cliargs.log)
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/Builder.py", line 526, in build
    self._compile(file_to_build=file_to_build, verbose=verbose, log=log)
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/Builder.py", line 462, in _compile
    result = syswork(cmd)
  File "/Users/anaconda/lib/python3.4/site-packages/fobis/utils.py", line 27, in syswork
    output = output.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 97: ordinal not in range(128)

```

**Comment by szaghi** [comment]
Hi Jacob, It is due to byte string "nightmare" of Python (I think). Can you give me a minimal example that raises the bug? Anyhow, I cannot fix it before oneweek... my first daugther is coming :-) !!

**Comment by jacobwilliams** [comment]
Congrats! Make sure you start teaching her Fortran early!  I'll post the minimal example later.

**Comment by jacobwilliams** [comment]
Some sort of non-printing control characters got into my source file somehow.  When I [deleted them](https://github.com/jacobwilliams/bspline-fortran/commit/83ccab14f300f1d128a1df54dae08f8359a64ebd) the problem goes away. Maybe it is not a big deal.

**Comment by szaghi** [comment]
Dear Jacob, thank you for the example. The next week (when my daugther come at home!) I will try to see the exotic characters raising the error. Probably, your Visual Studio is the "killer" :-) with vim you will have the control :-)

See you soon, I hope.

**Comment by jacobwilliams** [comment]
OK, I take back what I said.  I'm seeing this error again, even though (I think) I have no unusual characters in the file.  See the "refactor" branch [here](https://github.com/jacobwilliams/bspline-fortran/tree/refactor) (commit [1272a40784](https://github.com/jacobwilliams/bspline-fortran/commit/1272a407843f176aebb6080f25efca65dd10bbd5)). When I run the ```build.sh``` script (which is calling FoBiS) I see this error.  I'm using Python 3.4.2.

**Comment by Tobychev** [comment]
I remember having something similar happen to me, but I don't recall the fix. If you just look up what that unicode address is you learn that its RIGHT SINGLE QUOTATION MARK, hardly exotic. 

My (suspicious) recollection is that it had something to do with an error in my code, that produced an error message that killed FoBiS. However I'm very uncertain of how accurate this memory is.

**Comment by jacobwilliams** [comment]
Yes, it seems to have something to do with the error or warning messages emitted by gfortran. When I fixed the error in the code, the problem goes away (the commit after the one I referenced above).

**Comment by zbeekman** [comment]
Has this been fixed?
