### ISSUE TITLE
Unneeded conditional statement calling parse_args

### ISSUE THREAD

**Issue by sanguinariojoe** [szaghi/FoBiS#56]
In config.py:578:

    if fake_args:
      self.cliargs = cliparser.parse_args(fake_args)
    else:
      self.cliargs = cliparser.parse_args()

where fake_args is None by default, however from the documentation of the arguments parser:

https://docs.python.org/2/library/argparse.html#argparse.ArgumentParser.parse_args

    ArgumentParser.parse_args(args=None, namespace=None)

So calling directly to the following (without conditions):

    self.cliargs = cliparser.parse_args(fake_args)

Should be the same.

---

Also the comparisons with 'None' should be carried out with the 'is' statement:

    if fake_args is not None:

I hope it can helps!

**Comment by szaghi** [comment]
Yes, of course all your points are rigth. This is an example of my non-pythonic style... unfortunately (or fortunately) I am a Fortran poor man :-)

Thank you Pepe!

**Comment by szaghi** [comment]
Done
