### ISSUE TITLE
Catastrophic fail if a file is generated with the name of an output folder

### ISSUE THREAD

**Issue by sanguinariojoe** [szaghi/FoBiS#58]
I have not checked that, but I love the 'Catastrophic' word, and I'm almost sure that it's gonna happen...

In _sanitize_dirs() (Builder.py:145) FoBiS is checking if the path already exist before trying to create that, however it is not checking if the path is a directory or a file...

Therefore, creating a fancy file, let's say 'obj', _sanitize_dirs() is detecting it as a valid path, skipping, and exploding later with a terrible error hiding...

Am I right??

Enough for today!

**Comment by szaghi** [comment]
This is very interesting, I think you are rigth!

In general I have a particular "fortune" for raising catastrophic error, but in this case I completely miss this :-)

Today I will test and fix this.

Thank you very much Pepe!

**Comment by szaghi** [comment]
Correct, and purged out all `os.sep`.
