### ISSUE TITLE
Circular dependencies when two modules are present in the same file

### ISSUE THREAD

**Issue by perrette** [szaghi/FoBiS#63]
Nice feature to be able to generate makefiles. After experimenting around, it seems that it is not quite as reliable as executing the code directly though. In one project, I end up with the following block:

```
$(DOBJ)ioparams.o: ./src/ioparams.f90 \
        ...
        $(DOBJ)basalmelt.o \
        $(DOBJ)ioparams.o
        @echo $(COTEXT)
        @$(FC) $(OPTSC) -I/usr/include  $< -o $@
```

The circular arrow is visible on the dependency graph for ioparams:
![dependency_graph_main](https://cloud.githubusercontent.com/assets/1402264/8150820/b3e23ae6-12f9-11e5-9774-b68cb4d7b041.png)

The ioparams module contains two modules. The problem disappears when only one module is present.

Since it is automatically ignored in the makefile, this is not critical, but maybe it relates to other potential problems?

**Comment by szaghi** [comment]
You are touching one Achilles' heel of FoBiS.py... The generation of makefile is:

+ untested;
+ unsafe;
+ in general not used...

I will try to improve the makefile generation, however I have other priorities thus it will be fixed not so quickly. I am sorry.

Can you give me a working minimal example where this bug raises?

Thank you very much for your help in improving FoBiS.py.

My best regards.

**Comment by perrette** [comment]
Hi ! I think the issue is unrelated to Makefile, since the circular dependency is visible from the graph.
I will work out on a minimal example soon.

**Comment by perrette** [comment]
P.S.

a pity that Makefile generation does not belong to your priorities !
IMO, it is a convenient way of checking what FoBiS.py does (and very convincing for new comers grown up with Makefile).

Just curious: I have not digged into FoBiS.py internals yet (large classes tend to scare me), but could FoBiS.py build and clean command be based on simply these two steps:

- parse source files and compute dependency tree
- generate a makefile from dependency tree
- use GNU makefile ...

Or would it lose essential functionality? I would at least significantly simplify things, and transparently solve other issues such as timestamp (#61).

**Comment by perrette** [comment]
Here the minimal example:
```
! myprog.f90

program main
  use mymod
  call print_hello()
end program
```
```
! mymod.f90

module mod1
  integer :: i = 1
end module

module mymod
  use mod1
contains
  subroutine print_hello()
    print *, "hello ", i
  end subroutine
end module
```

Generates 
![dependency_graph_myprog](https://cloud.githubusercontent.com/assets/1402264/8157039/9e5e4d1a-1351-11e5-879e-3abfaae26b0a.png)

And a makefile would show:
```
$(DOBJ)mymod.o: ./mymod.f90 \
        $(DOBJ)mymod.o
        @echo $(COTEXT)
        @$(FC) $(OPTSC)  $< -o $@
```

It is not even wrong (any file depends on itself...), but it is redundant. 

A simple workaround (for both file and graph) would be to remove any dependency that is the same as the target...

As far as the graph generation is concerned, another interesting aspect would be to show module dependency. This "error" lets me think that internally, FoBiS.py compute actual module dependency, so why not showing it? It is a robust diagnostic for the code, which is independent on how various modules are organized in files (in python modules and files are the same, but in modern fortran modules are the only semantic aspect)

**Comment by szaghi** [comment]
I am sorry, I completely miss this... but the graph is generated by FoBiS.py?

**Comment by perrette** [comment]
yes! 
`FoBiS.py build -compiler gnu -graph`

**Comment by szaghi** [comment]
@perrette 

For the "algorithm" of FoBiS.py... I have to accurately check, but I think that is as you depicted:

+ FoBiS.py parse each source files it found:
  - tag the source as to be one of:
      * program;
      * module;
      * included file;
      * a non-module library (old Fortran file with a messy of procedures...);
  - construct the dependency of each parsed filed;
  - build its target (or all program it had found);

A a consequence the other two steps you suggest is done as you said:

+ from the computed hierarchy build the makefile (that is probably now bugged);
+ use make for testing FoBiS.py correctness.

**Comment by szaghi** [comment]
@perrette 

Ok, I try to purge out dependency that is the same of target into makefile rules.

**Comment by perrette** [comment]
About the algorithm you described:

- I found cases where both module and non-module libraries are present in the same file... Normal fortran compiler takes it... Not sure whether FoBiS.py should account for such cases (maybe not, keep it simple for well-programmed code...), but currently normal compilation works fine because when the module is compiled, these other libraries are as well, even though the dependency tree is broken (surprisingly the same is not true with makefile)
- How can the makefile be bugged and FoBiS.py work properly, if FoBiS.py does rely on "make" ?

**Comment by szaghi** [comment]
FoBiS.py does not rely on make.

The compilation hierarchy creation seems to be correct (at least I have not yet found a case where FoBiS.py does not correctly build the target), however the method that convert from *FoBiS.py representation* and the final makefile can be (I almost sure it is) bugged.

For the mixing of module and non-module contents into a single file... not I do not covered this case, I am crazy but not so much :-)

**Comment by perrette** [comment]
legacy fortran code ...
maybe breaking compilation in such cases would force developer to clean up the mess in the first place
FoBiS.py is less tied to back-compatibility than gfortran is...

**Comment by szaghi** [comment]
>legacy fortran code ...
maybe breaking compilation in such cases would force developer to clean up the mess in the first place
FoBiS.py is less tied to back-compatibility than gfortran is...

You are right :-) !

 Indeed, I become a troll with old-messy-legacy codes... I am sorry.

**Comment by perrette** [comment]
Maybe the fix could be to write targeted error message "Your source file seems to be a mess, please use modern fortran and encapsulate your routine into a module for FoBiS.py to process it correctly. " :)

**Comment by jacobwilliams** [comment]
Having FoBiS generate the module dependency graph would be interesting.  What are you using for that? ([Graphviz](http://www.graphviz.org)?)  

That might also be a nice feature for documentation purposes (maybe in [FORD](https://github.com/cmacmackin/ford)). What do you think @cmacmackin?

**Comment by szaghi** [comment]
Sure, I was trying to support this just for FORD (helping Chris). I was thinking that it was broken, @perrette just shows me that I was wrong...

Anyhow, yes I am currently using Graphviz.

**Comment by szaghi** [comment]
In new version 1.7.1 the circular dependency of the generated makefile is eliminated.

I have added a specific unit test `src/unittest/python/makefile-test1/`

> note that the circular dependency is not remove from the generated graph: indeed I prefer to not completely remove it because it is true that mymod module depends on mymod.f90 two times... however in the future bug-fix/improvement I will try to change it if required by a specific issue :-)

P.S. yes, FoBiS.py must compute the modules hierarchy: if you build with log activated it saves the hierarchy for checking what really happens.

**Comment by cmacmackin** [comment]
I would certainly be happy to have this feature in FORD. I've been thinking a little bit about how to implement something like this for awhile and the only thing which has held me back is my lack of familiarity with tools like Graphviz. Not that I can't learn it--it's just been easier for me to focus on other issues (such as links to different parts of the documentation, which will be done very soon, @jacobwilliams) which don't require me to learn a new library.

**Comment by szaghi** [comment]
@cmacmackin 

ASAP I will try to extract the graphic generation for FORD. Indeed, it is now very *trivial*, this is the reason I left this feature almost *hidden* ( @perrette shock me using it...).
