### ISSUE TITLE
feature request: line numbers in gcov report for uncovered functions

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#66]
I know you’re super busy, and this is not at all urgent, but it would be nice to have line numbers included along with the procedure name in the uncovered procedures list generated by FoBiS.py. This is particularly applicable when internal procedures are present and there may be more than one with the same name.

Also, a very small bug: it seems to be picking up abstract interfaces too, see for example, `array_callback_func` in the coverage report [here](https://github.com/jacobwilliams/json-fortran/wiki/Coverage-Analysis) and its definition [here](https://github.com/zbeekman/json-fortran/blob/master/src/json_module.F90#L561).

**Comment by szaghi** [comment]
Lines number inserted (v1.7.3 in both PyPi and github). 

However, I cannot see the small bug on array_callback_func (that seems not present into the coverage wiki page you linked). Open a new issue for this with some more details.

See you soon.
