### ISSUE TITLE
Create fobos template from FoBiS.py

### ISSUE THREAD

**Issue by szaghi** [szaghi/FoBiS#67]
It can be very useful add FoBiS.py the ability to create a fobos template with all fobos-sugar enabled (@perrette idea!).

**Comment by Tobychev** [comment]
Isn't it better to host templates with the documentation? Expanding FoBiS into a document generation system doesn't strike me as an obvious extension to a Fortran build system, and the fobos file is intended to be human readable and editable anyway.

**Comment by szaghi** [comment]
@Tobychev 

Hi Tomas, nice to read you again.

I think that "both solutions" are welcome. The documentation *must* host fobos templates (I have update the doc, sorry), but it could be very handy to have an *on-the-fly-generated* general-template when the documentation is not under your fingers.

Even if I have not pushed updates for a while, my local branch(es) contains many improvements: soon I will push some new releases containing also this feature. However, consider that is just another optional flag: the nature of FoBiS is not changed, it just help humans to write their own fobos.

What do you think?

**Comment by Tobychev** [comment]
Hello  Stefano, nice to talk with you again :)

Actually, I realized I don't know how the template generation would work, and that I only object to some of the possible implementations.

Do you mean you added a flag that will make FoBiS generate a fobos file matching the currently supplied command line switches?

**Comment by szaghi** [comment]
@Tobychev yes!

something like (introspection...):

```shell
FoBiS.py gen_fobos_template
```
and a *fobos_template* file is generated with all the currently supplied options (that should be the same for the command line and for the fobos file).

**Comment by Tobychev** [comment]
I would suggest  something like

> FoBiS.py build -ext_libs foo --lib_dir /strange_path_to/my_libraries/ --write-fobos

and I recognized an issue for debate: how much should this flag generate? Should it generate a fobos file with only the settings supplied on the command line included, or with all the possible settings set to their default values? Maybe some definite subset of all the possible settings, or maybe it should have some defined subset of *required* values before it generates anything?

The responses to this issue should consider who we imagine would use the feature, I think probably just experienced users should use it, and newcomers should use the templates in the documentation. In particular this means I think it should generate as small a fobos file as possible while still making something that can build. This means the last suggestion, where FoBiS will exit with an error if the command line arguments does not contain a build target for instance.

**Comment by szaghi** [comment]
@Tobychev @perrette

In the new 1.9.6 version there is an option to print to standard output (thus you can redirect it to a file) a comprehensive fobos template with all available options.

Other fobos features, e.g. rules/variables/templates, are not currently explained into the printed template.

Give me your opinions when you like.

Thank you for help!
