### ISSUE TITLE
Extend FoBiS.py to other languages?

### ISSUE THREAD

**Issue by perrette** [szaghi/FoBiS#68]
That is a nasty issue, and it even contradicts the name of the project...
As [Alex](https://github.com/alex-robinson) mentioned to me the other day, @szaghi did a lot of work in FoBiS.py to work-out concepts, a workflow, a user-interface...and actually very little of this is really Fortran specific. Why not extend this to, say, C/C++ ? 
As a disclaimer: I am not a C/C++ programmer, so I cannot even help. I was just curious, especially when searching for libraries the other day, that only existed in C++. I mean, this is really a common use-case, right? And a two step C++ Makefile / FoBiS.py --ext_vlibs does not make a very clean build script. So presently, this kind of situations are a push toward CMake (and its horrible, multi-directory configuration files). 

So I was wondering, what would it cost to have it extended to C/C++? Just thinking 2sec:
- have a C++ parser that builds the dependency tree
- workout compiler options ... ( -compiler gnu => g++)

My 2 cents (talking...)

**Comment by szaghi** [comment]
This is a good point. A like KISS tools doing few things but doing them right. As a fortran addicted I does not need to support other languages, hover the mixing languages scenario is very diffused. Consequently, the answer is yes, I can try to support C/C++ mixed fortran project. However there is a big issue... I don't know C/C++ (indeed I don't like them at all).

 I learned them very superficially (never used in a real application). This means that I have to study a lot things. If you or some of your collaborators will support me, I will try to implement, but without any help this feature request will need a long time before *see the sun*.

Your 2 cents are always appreciated :-) please feel free to ask me all requests you thinked to... also the crazy ones... mixing fortran with others is a crazy idea :-)

See you soin

**Comment by perrette** [comment]
Of course, only a C/C++ programmer could help here. Maybe a way forward then, would be to specify what FoBiS.py needs to work with other languages. Try to identify in the code what is fortran-specific (e.g. build a dependency tree of source files, compiler-specific options) and what is actually more conceptual (all the rest). Some kind of FoBiS.py internal API. As far as the compiler-specific part is concerned, maybe just start with one compiler (e.g. gnu). And at some point change the name ;-) (or the meaning of the FoBiS.py acronym).

**Comment by szaghi** [comment]
Basically we must:

+ add new compilers supported by the class *compiler*;
+ know the C/C++ compilation cascade (if any);
+ know the mixing fortran/c/c++ *interaction* (the link between them).

The other fobis classes should be sufficient general.

Finally, the name will not change: I plan to support mixed projects only for the poor fortran people... fortran will remain our *soul*, c/c++ are *incidents* :-)

I will (re)start to play with some c excercises.

P.S. the makefile generation should be ok in the current version: do you have tested it?

**Comment by zbeekman** [comment]
May I suggest that you only support mixed language through use of `ISO_C_BINDING` and `bind(c)` rather than trying to do what they did in the bad-old-days dealing with wacky name mangling concerns and all that stuff? I think FoBiS.py works so well for Fortran, and you shouldn’t make it too big and unwieldy to support C/C++ too… just my two cents.

**Comment by szaghi** [comment]
@zbeekman very good observation... I do not nothing about the **bad-old-days**... surely if I will support c/c++ is just for only mixed fortran /c /c++: c programmers are full of nice build tools better than fobis that should remain kiss. The hint on using iso_c_binding and bind(c) is very nice. Remain the problem that I never do a mixed code and I have to study a lot...

**Comment by zbeekman** [comment]
Yes, I guess my point is, it could be very cool to support C/C++/Mixed code, but it should be very low priority relative to supporting Fortran and what you’ve done so far… You don’t want to make FoBiS bigger than it needs to be, in my opinion.

**Comment by jacobwilliams** [comment]
C++ is terrible. Nobody uses it anyway. :)

**Comment by szaghi** [comment]
@jacobwilliams :+1:  

however, the world is nice because 100 programmers use 100 different languages... we have to be patient with people not so lucky as us :-)

**Comment by perrette** [comment]
@jacobwilliams  Well, C++ is far more flexible than fortran is, and as a result with a signifcantly more complex syntax (not sure whether the syntax thing needs to be - python is also very powerful while keeping a simple syntax - but as a matter of fact C++ syntax is complex). Fortran is easier to read (except for the horrible `%` syntax for the type variables/method access), and its simplicity also makes it easier for the compiler to handle memory allocation and array optimization - two nice characteristic to write and share scientific code. Nevertheless, the flexibility of C++ (and the type-generic classes !) makes it very cool to program fancy object-oriented code. That's probably why there are so many C++ libraries out there.

I agree with @zbeekman, keep it simple, `iso_c_binding` is the way to go as the "linkage". That is the only one I know anyway. But I am not sure whether this changes much regarding to what needs to be implemented in FoBiS.py. Even with `iso_c_binding`, the C code needs to be compiled, and as such code parsing and dependency tree building on the C/C++ side needs to be done anyway... Where it can remains KISS, is by keeping the language-specific parts distinct from each other. Not sure how it is right now, but it may actually ensure that FoBiS.py code is cleanly written and nicely modular. In my understanding, the only use of assuming `iso_c_binding` interface is to say FoBiS.py that we deal with _mixed_ language code (as soon as `use iso_c_binding`) is detected in a dependency... Apart from that, the compilation remains separate and the objects only need to be indicated in the linkage step, no?

@szaghi : if it is true that supporting C/C++ with iso_c_binding involve much C/C++ specific processing steps anyway, having a slightly broader scope may actually help to attract the attention/interest of C/C++ programmers, and to have more support on this side. So I would suggest to keep it open (to the extent it does not change much to the KISS aspect of it).

**Comment by Tobychev** [comment]
I think that the primary reason for FoBiS is to build Fortran code, and that not much good will come from forcing poor fortran stefano to learn C++.  

From what I understand, even with iso_c_bind, the process of building some fortran calling c does not actually involve any interaction between the sources. It is only at the linking stage that there is any contact between the langauges, so it seems to me that it is in fact just a special case of using an external library. 

So it seem that to handle the case where Fortran code depends on libraries in other languages FoBiS should have the ability to quite blindly invoke some external build system (specified by the user) that in turn builds the library. I recall there being some discussion about how to automatically rebuild external fortran langauges, so I guess a good start would be to look at that and see if you could just slap in an execution of some user specified shell command.

**Comment by zbeekman** [comment]
I agree with @Tobychev , FWIW

**Comment by perrette** [comment]
@Tobychev 
> it is in fact just a special case of using an external library.

That is also my understanding, but does not change much to the original issue:
> @szaghi did a lot of work in FoBiS.py to work-out concepts, a workflow, a user-interface...and actually very little of this is really Fortran specific

and 

> a two step C++ Makefile / FoBiS.py --ext_vlibs does not make a very clean build script. So presently, this kind of situations are a push toward CMake (and its horrible, multi-directory configuration files).

To me at least...That's why I'd suggest paving the road for any C++ programmer to help with parsing C/C++ (via an internal FoBiS.py API). I actually do not see why this would make the whole thing so much more complicated. Or is there something so different in how C++ compilation/linking work??

**Comment by perrette** [comment]
The only place where I could see an additional complexity caused by supporting C++, is indeed compilation options. I guess the options overlap to a certain extent, but are not equivalent. So a new aspect would be to provide, like CMake does, different build types such as _debug_ or _release_ and with it associate a set of options for each compiler.

Ok, when thinking in detail about the user-interface though, it **does** become more complex, because you need to provide certain command-line parameter twice. E.g. `--cflags` and `--lflags` would need to be rename to distinguish between fortran and compilers (`-fc` is fine, would just need to be supplemented by `-cc`). User interface *is* an important aspect that determines whether a tool becomes widely used or not (otherwise you guys would have been using CMake and @szaghi would never have started working on FoBiS.py). 

If UI and back-compatibility becomes an issue, then maybe the wisest step in that direction would be to start a new project that branches from FoBiS.py, that would be more general (designed for fortran and C/C++ from the start, maybe another name) and keep FoBiS.py as it is for now. A question then would be, how to make such a parallel development constructive (bug fixes in one portable to the other project). This is probably the point where I would close this issue, and forget about it for now...

**Comment by perrette** [comment]
Or less dramatically, prefix command-line parameters with `-c`, such as `--c-cflags` and `--c-lflags`.

**Comment by Tobychev** [comment]
Well, there are already several [build systems](https://github.com/fffaraz/awesome-cpp#build-systems) for C++, and looking at two of them (Ninja, thundra) their github repos have issue counts in the hundreds, 101 and 23 commiters, and Ninja has over 2k commits. 

So from casual inspection it does seem like build systems for c++ could be a bit complicated to implement.

**Comment by perrette** [comment]
It could be (I really don't know)...but the number of commits is not a really convincing argument. FoBiS.py currently has 153 commits... I guess any program can be extended indefinitely, regardless of its level of complexity, right? (I believe this is called [code inflation](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7057573))

**Comment by perrette** [comment]
(the number of commits could simply mean that C/C++ is used by far more people than fortran is, because C++ is a more general language)

**Comment by perrette** [comment]
(I do not want to start another polemic, but quite unsurprisingly : http://readwrite.com/2012/06/05/5-ways-to-tell-which-programming-lanugages-are-most-popular -- I realize this is really specific to the field of use, and I am very happy to use fortran for my applications, as mentioned in the issue - nevertheless, it would be blind to ignore that C++ is used in far more applications)

**Comment by szaghi** [comment]
Dear all, it is to early for say that a way i better than other. My feeling is:

+ if Fobis will support mixed codes the reason is not for increasing the tool popolarity (I do it for my self and give it back to the gnu community for ethic reasons) rather for better support poor fortran people that have to face with mixed fodes;

+ the critical part is (imho) the compilation hierachy of c/c++ (if any) rather than the options: as the things are now dhould be quite easy to support other compilers (feature that was added for fortran but is language agnostic and can be applied to c / c++ compilers);

+ the compilation hierarchy is my pain: for the fortran I spent some times for building up the correct regex/logic/case-(in)-sensitivity and so on; I am hoping that iso_bin_c can help for decting the minimal requirement for the compilaton of the mixed code but I really do not know;

+ the c flags will be added with new cli options, there is no reason for breaking bacward compatibility: fobis will remain a tool for fortran, the mixed c support will be a plus.

Anyhow I need some times to try to help buoldings of mixed code.

Thank you all gor great suggestions, your help is very appreciated!

**Comment by perrette** [comment]
> if Fobis will support mixed codes the reason is not for increasing the tool popolarity (I do it for my self and give it back to the gnu community for ethic reasons) rather for better support poor fortran people that have to face with mixed fodes;

Sure. I was just thinking. The larger the public, the more potential contributors, the more robust the tool becomes. It would be a pity not to seize the opportunity (assuming you already did most of the work).

Let's hope a C++ regular-expression freak will jump in ;-)

**Comment by szaghi** [comment]
@perrette  :+1:

**Comment by szaghi** [comment]
Currently, I have not the time to implement this feature request and no others seem to be interested. I am closing it, but in the future, I can re-try to re-think to it.

Cheers.
