### ISSUE TITLE
[feature request] link-ify procedure names in gcov analyzer for FORD

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#72]
I’m contemplating adding FoBiS.py generated gcov coverage reports to the automatically deployed and generated JSON-Fortran documentation. (You can easily add it to a “pages” directory. All it needs is the additional `title: …` meta data header to be a valid FORD “pages” page.) It would be amazing to also then wrap the procedure names in the report in double brackets (with the `proc` marker): https://github.com/cmacmackin/ford/wiki/Writing-Documentation#links. It the output would look like:

`[[<procedure_name>(proc)]]`

This way FORD will link to each of the procedures mentioned.

**Comment by szaghi** [comment]
Nice hint! Tomorrow I should find the time for our group and FoBiS, stay connected.

**Comment by szaghi** [comment]
Sorry, can you post a minimal complete example of the desiderata mardown report? Thank you Zaak

**Comment by zbeekman** [comment]
I may try to submit a PR for this. It seems that the coverage analysis is only looking at subroutines right now and I would like to add functions and fix its picking up of abstract interfaces. At any rate, I didn't have time today to get you an example. I can do this tomorrow.

**Comment by zbeekman** [comment]
I’ve decided that this task is simple enough to just use shell scripting to accomplish. It just involves surrounding procedure names in double square brackets.  `*subroutine* **My_sub** …` becomes `*subroutine* **[[My_sub]]** …` which will cause FORD to create a link to it. If no such procedure exists (say because it is an internal procedure) then FORD does not create a link, and the double brackets just get printed in bold with the procedure name. Here is the sed script I use:

```bash
sed -i"bak" -E 's; \*\*([a-zA-Z]+[a-zA-Z0-9_]*)\*\*; \*\*[[\1]]\*\*;' json_module.F90.gcov.md
```

**Comment by szaghi** [comment]
Hi Zaak, thank you for sharing. 

I have a question: due the last very busy period, I have missed many updates of FORD and I do not know how you and Jacob have created the *additional documentstion  pages* of json-fortran. Do you have aldo integrated the wiki?

**Comment by zbeekman** [comment]
The additional documentation pages of json-fortran use the FORD “pages” feature: https://github.com/cmacmackin/ford/wiki/Writing-Pages

**Comment by zbeekman** [comment]
They aren’t integrating the wiki, but dedicated pages written in markdown and stored in the “pages” subdirectory
