### ISSUE TITLE
Create a PyPi release

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#74]
Hi Stefano,
Could you please create a PyPi release to include the bug fixes from the PR I submitted a while ago? Without this, JSON-Fortran’s Travis-CI documentation build will have some flaws, since it is using an old version of FoBiS.py

**Comment by szaghi** [comment]
Sure, I am very sorry for my delay, in a couple of hours I will upload the new release.

**Comment by szaghi** [comment]
Done, v1.7.4. should be in both PyPi and github. Thank you zaak!

**Comment by zbeekman** [comment]
Thanks so much!
