### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by cmacmackin** [szaghi/FoBiS#75]
Seeing as ifort now supports [submodules](http://fortranwiki.org/fortran/show/Submodules) and it looks like gfortran [isn't far behind](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52846#c2), it might be worth making FoBiS aware of them and how the affect dependencies and the build order. (Just something that was on my mind since I want to implement support for them in FORD before the next release.)

**Comment by szaghi** [comment]
Great Chris,

I think that before FoBiS, you must make me aware of them :-) I have not yet found the time to learn this new feature. Can you link some nice resources (tutorials, examples, books)?

Thank you very much for the hint!

**Comment by cmacmackin** [comment]
Well, I'm not that familiar with them myself, to be honest. The first link I provided gives an overview of how they work. For a more detailed (and technical) discussion see [this document](ftp://ftp.nag.co.uk/sc22wg5/N1601-N1650/N1602.pdf). Another description can be found [here](ftp://ftp.nag.co.uk/sc22wg5/n1801-n1850/n1828.pdf).

**Comment by szaghi** [comment]
@cmacmackin In your last post seem that the hyperlinks are missing.

**Comment by cmacmackin** [comment]
Sorry, I think that's because they were linking to documents on an FTP server and GitHub was looking for HTTP/HTTPS. The URLs are ftp://ftp.nag.co.uk/sc22wg5/N1601-N1650/N1602.pdf and ftp://ftp.nag.co.uk/sc22wg5/n1801-n1850/n1828.pdf, respectively.

**Comment by szaghi** [comment]
Do not worry, thank very very much!

**Comment by szaghi** [comment]
The time to study and im0lement it is arrived. I am going... :pray: for me

**Comment by szaghi** [comment]
Readings

+ [yellow submodule](https://software.intel.com/en-us/blogs/2015/07/07/doctor-fortran-in-we-all-live-in-a-yellow-submodule?language=de)

**Comment by szaghi** [comment]
Done in the incoming v2.0.0.
