### ISSUE TITLE
FoBiS not detecting changes to source

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#80]
I occasionally encounter a bug when making changes to ```json-fortran```, where FoBiS doesn't quite keep up. For example, I just had a situation where I changed the name of a routine, ran FoBiS, and it seems to compile everything again, but I got a linker error that was referencing the old name that wasn't there anymore. Deleting the bin and lib directories didn't help. Checking out a fresh repo and copying the same files over, it worked fine. So, FoBiS was caching something or some information was persisting? Is it saving files somewhere (I couldn't find any)?

**Comment by szaghi** [comment]
Hi Jacob,
This is quite strange. I accont help now, monday I will try to investigate deeply. Can you provide a minimal example raising the bug?

Thank you for the feedback.

**Comment by szaghi** [comment]
Hi Jacob,
I try to replicate the bug, but I am not able to do it.

FoBiS should not cache nothing. It compares the time-stamp of sources with the compiled objects for all the dependencies of each target: it sources and compiled objects are not in sync they will be recompiled (some circumstances trigger to recompile all also, e.g. heritage cflags option that you use).

Please, give me a minimal example or let me know the steps you perform on json-fortran to raise this bug.

Stefano

**Comment by jacobwilliams** [comment]
Will try to create an example, but it's hard to reproduce.

How does FoBiS save the time stamps and the compile flags? Is that being written to a file somewhere?

**Comment by szaghi** [comment]
Il you activate cflags heritage the cflags are saved into an hidden file
into build dir. The time stamp are not saved are inferred from OS.
Il 02/nov/2015 17:52 "Jacob Williams" <notifications@github.com> ha scritto:

**Comment by szaghi** [comment]
@jacobwilliams Are there some *news*?

**Comment by jacobwilliams** [comment]
I'm swamped right now. If you leave the ticket open, I'll try to duplicate it and send you a reproducer. But, I don't know when I'll be able to get to it.

**Comment by szaghi** [comment]
@jacobwilliams sure, do not worry, take all the time you need.

Thank you for your help.
