### ISSUE TITLE
track Homebrew install stats?

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#81]
Hi @szaghi, I was about to update the FoBiS.py formula for the latest release, and was wondering if you were interested in tracking the FoBiS.py installations through Homebrew. Just let me know and I can ask the Homebrew maintainers to make this information public. Here are some example stats for `a2ps`: https://bintray.com/homebrew/bottles/a2ps/view#statistics

**Comment by szaghi** [comment]
Dear @zbeekman 

You are very kind!

I completely forget about the Homebrew install! As I said in the similar FOODIE topic, feel free to add the stats tracking. Let me know I can help you.

I like to add the instructions on how install FoBiS by means of Homebrew. Can you help me? How OSX users can install FoBiS?

Thank you very much.

P.S. I will add install instructions also in the README, it seems that now this information is only into wiki.

**Comment by zbeekman** [comment]
Here is a link to the download statistics: https://bintray.com/homebrew/bottles/fobis/view#statistics This is an under estimate due to the face that some people may install the HEAD version which isn't bottled and because until my PR with formula updated for the most recent release is accepted, no El Capitan bottles are available.

To install with Homebrew:

```
brew update         # fetch most recent formulae
brew install FoBiS  # install FoBiS.py
brew test FoBiS     # optional test to ensure that FoBiS.py is correctly installed, requires Fortran compiler
```

**Comment by szaghi** [comment]
@zbeekman wow, thank you very much! You are very kind!
