### ISSUE TITLE
manual install

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#82]
Now that you've cleaned up the `release` folder, and everything is working through PYPI/`pip` could you please update the [manual install directions](https://github.com/szaghi/FoBiS/wiki/Manual-Installation) and explain how to install the `master` HEAD with `easy_install` or similar?

**Comment by zbeekman** [comment]
(P.S. if this get's done soon enough, I will add the `head do` block to the [homebrew](https://github.com/homebrew/homebrew) formula, as I am working on submitting the 1.9 release PR request now)

**Comment by szaghi** [comment]
:+1:  tomorrow I hope

**Comment by zbeekman** [comment]
If you get to it before the Homebrew maintainers accept [my pull request](https://github.com/Homebrew/homebrew/pull/47822) I'll update the formula to allow for HEAD installations from Github. Otherwise, I'll sneak it the next time you release an updated version of FoBiS.py

**Comment by zbeekman** [comment]
any chance this made it into the latest release?

**Comment by szaghi** [comment]
Ohhhhh, I am very sorry Zack, I completely forget this! The last two weeks were *heavy*... The next week should be better, I hope to do this very soon, my apologize! :pray: 

Cheers

**Comment by zbeekman** [comment]
no worries

**Comment by szaghi** [comment]
Hi @zbeekman 

Can you recall me what you need for the manual installation? You mention `easy_install` in your PR, but this makes me confused.

Presently FoBiS is installed via PyPi. Manual installation should be easy (I can update the wiki instruction simply pointing to the `src` directory rather than the `release` one), but I feel I am missing the *important point*: which is the best (standard) way to manual install a Python code? If you have some suggestions (links, advice) please help me. 

I am going to *sanitize* FoBiS, this could be the right time to fix the manual installation.

Cheers.

**Comment by zbeekman** [comment]
@szaghi My goal is to be able to install FoBiS.py directly from the master branch on Github. Sometimes I might want to test out fixes or new features before you've had a chance to create a release and publish it on PyPi. Right now, if I go into the old releases directory I can do something like this:

```
cd release/FoBiS-1.8.4
pip install .
```

There should be a way to install the master branch with some similar procedure. How can I install the master branch, without waiting for a release? I would like to encode this procedure in the Homebrew formula, so users can install the master branch with `brew install --HEAD FoBiS` The procedure for generating PyPi releases from master is not obvious to me. Knowing this, would be a step in the right direction for being able to install the master branch.

**Comment by szaghi** [comment]
@zbeekman Wonderful, now it is very clear. Soon this day I solve this issue.

Thank you very much!

**Comment by zbeekman** [comment]
Great. Let me know if you have any other questions.

**Comment by szaghi** [comment]
@zbeekman 

Hi Zaak, all is done.

Currently, I am tracking only 1 release, namely `release/FoBiS-master`, that is provided only for the purpose to facilitate a manual installation (very useful for also virtualenv stuff that I am experimenting in these days for improving the support of Python 3.x). The simple procedure to perform a manual installation is:

```shell
cd release/FoBiS-master
python setup.py install
``` 

In the future other release could be tracked, but the master one is the only that surely will be shipped with the project.

I am updating the wiki right now.

Let me know if this is good for you.

Cheers.

**Comment by szaghi** [comment]
@zbeekman 

I am closing this, feel free to reopen it if the manual installation procedure is not good for you.

Cheers.

**Comment by zbeekman** [comment]
Hi @szaghi thanks for doing this. In the short term this will suffice, however, the real question is this:

How did you generate the release/master directory?

Because then you don't need to remember to update it when you push additional changes. If I (or the "user") has this information then you don't have to maintain an additional release (named "master")

**Comment by szaghi** [comment]
@zbeekman 

I use pybuilder. When a new release is out from its master branch I build locally a release by [pybuilder](http://pybuilder.github.io/) (trough `build.py` script):

```shell
cd FoBiS
pyb
...
```
this creates into `release/FoBiS-master` a *compiled* release suitable for PyPi upload and for a manual installation.

**Comment by zbeekman** [comment]
Bravissimo! Just what I was looking for, thank you! It seems there are some dependencies that need to be satisfied to use this, but that's totally fine, I can figure those out!

I might suggest removing the releases/FoBiS-master directory from git source control, and just telling people to use `pyb` for manual install....

**Comment by zbeekman** [comment]
:bow: :clap: :tada: :100:

**Comment by szaghi** [comment]
@zbeekman 

>Bravissimo! Just what I was looking for, thank you! It seems there are some dependencies that need to be satisfied to use this, but that's totally fine, I can figure those out! I might suggest removing the releases/FoBiS-master directory from git source control, and just telling people to use pyb for manual install....

Yes, it has some dependencies. This is the reason why I do not cite it into the doc. Indeed pybuilder is very useful, I use it for 3 aims:

+ deeply test FoBiS in my local workstation;
+ easily repeat the thourogh tests on travis that is very different from my local setup;
+ easily create a release-build suitable for PyPI.

All things by simply running `pyb` :smile: 

I will follow yoyr suggestion: I will cite pybuilder and untrack the `releae/FoBiS-master` directory.

As always thank you very much!
