### ISSUE TITLE
rules doesn't support using variables

### ISSUE THREAD

**Issue by zhouguidi** [szaghi/FoBiS#86]
Hi,

Currently FoBiS does not support using variables in rules. Consider the following minimal example:

[common-variables]
$MSG = this is a message

[rule-install]
rule = echo The message is: $MSG.

Running FoBiS.py rule --execute install would print the following:

Executing rule "install"
   Command => echo The message is: $MSG.
The message is: .

Apparently the variable is not recognized.

Please fix this. Thanks!

Guidi

**Comment by szaghi** [comment]
@zhouguidi 

Hi Guidi, thank you very much for reporting it. Indeed, it should work, I use it for c/l-flags, but I never tried with rules... this is a real bug!

I'll try to fix very soon (today I hope).

Stay tuned.

**Comment by szaghi** [comment]
Dear @zhouguidi 

In the new version 2.1.0 on both GitHub and PyPi, I have just uploaded a patch that should solve this issue: global variables are usable into also rules.

I am closing this issue, feel free to reopen it in case the new patched version does not work for your cases.

Thank you for your help.
