### ISSUE TITLE
Additional options for use with spack

### ISSUE THREAD

**Issue by cmacmackin** [szaghi/FoBiS#87]
Hi Stefano. As I've been writing my own scientific Fortran software as part of my degree, the need to manage dependencies has become increasingly important. As such, I've finally turned my attention to a package manager again. I've been looking at [spack](http://spack.readthedocs.io/en/latest/index.html), which should allow for easy dependency resolution and a simple build process for the end user. Rather than have to mess around with CMake, it would be nice to be able to use FoBiS with spack, but there are a few small issues which I foresee there.

The most important is that spack specifies the compiler via environment variables (`FC` for modern Fortran). It would be great if there was a way to get FoBiS.py to read the compiler from there. Another useful feature would be the existence of an `install` command. I suppose this could be achieved with a job defined in the `fobos` file, but that requires package maintainers to remember to write it. This command would need to have some way to specify the install-prefix.

These aren't absolutely vital--spack has enough features to be able to make FoBiS work as it exists now. But they would make life easier and reduce the overhead needed whenever a FoBiS-built project is packaged for spack.

**Comment by szaghi** [comment]
@cmacmackin 

Dear Chris, I remember a little bit of spack in our discussions on FLATPack.

The description you made about the improvements to be done on FoBiS let me consider them *very simple*: I think I can done them very quickly. However, I need your help to drive me: I have not completely understand what `install` should do. If you can provide me an example to work on it can speedup my work a lot. From your description I think that `install` looks like a new command of the level of `build`, `clean` and `rule`, but I am not sure about what `install` is intended to do.

The environment-driven settings should be quite simple. 

Let me know more details about `install`.

Cheers

**Comment by cmacmackin** [comment]
Sorry for my slow response. I needed to actually start working with FoBiS.py within FLATPack to get a sense of the answers to your questions. The first request, for the compiler command to be set from an environment variable is less important than I thought, because this can easily be overridden from the command line. The second remains useful, however. What I mean by install is that it would be nice if FoBiS.py could keep track of files produced in the most recent build command (executables, libraries, modules) and then have a command to copy them to the standard locations within a Linux file hierarchy, given some prefix. For example, I could specify the prefix `${HOME}/.local` and then it would copy executables to `${HOME}/.local/bin`, libraries to `${HOME}/.local/lib`, and module files to `${HOME}/.local/lib`. So the installation procedure might go something like this:

```
FoBiS.py build -mode WHATEVER-BUILD-MODE
FoBiS.py install --prefix ${HOME}/.local
```

It might also be nice to be able to specify files which should be excluded from the install process, particularly if you don't want all module files to be made available to the end-user of a multi-module library. Having some way to add documentation to the install command would also be nice, but would probably be more difficult, so it's not as big a deal if it is missing.

**Comment by szaghi** [comment]
@cmacmackin 

Dear Chris,

> Sorry for my slow response.

Do not worry.

> I needed to actually start working with FoBiS.py within FLATPack to get a sense of the answers to your questions. The first request, for the compiler command to be set from an environment variable is less important than I thought, because this can easily be overridden from the command line. The second remains useful, however. 

Ok, I change their priorities.

> What I mean by install is that it would be nice if FoBiS.py could keep track of files produced in the most recent build command (executables, libraries, modules) and then have a command to copy them to the standard locations within a Linux file hierarchy, given some prefix. For example, I could specify the prefix ${HOME}/.local and then it would copy executables to ${HOME}/.local/bin, libraries to ${HOME}/.local/lib, and module files to ${HOME}/.local/lib.

Ok, this can be done, but it requires a *non trivial* choice, I guess. Taking track of *old* building is already done for other purposes: FoBiS has the concept of *compiling heritage*, if you activate the heritage the whole building is completely re-done if the compiling flags change from one building to the subsequent one. The tracking is done by saving a hidden file and this is the choice that we must made (I think), how to track the building. I can think to 2 simple ways:

1. modify the current compiling heritage to save also what it has been (and not only how) thus using this file not only for the next build, but also for the possible next install;
2. create a new hidden file only for the install purposes.

Other ways to *easily* track the building are not clear for me, but if you have other suggestions they are much more than welcome.   

> It might also be nice to be able to specify files which should be excluded from the install process, particularly if you don't want all module files to be made available to the end-user of a multi-module library. Having some way to add documentation to the install command would also be nice, but would probably be more difficult, so it's not as big a deal if it is missing.

I also had the similar desire. Currently, I *integrate* FoBiS and FORD by means of *rules*: al my fobos files have a rule to build API doc using FORD. If you have suggestions for a more tight integration they are also much more than welcome. 

Cheers

**Comment by szaghi** [comment]
@cmacmackin 

Dear Chris,

in the just uploaded master branch I have added this feature. I have added 2 dedicated tests, [one](https://github.com/szaghi/FoBiS/tree/master/src/unittest/python/install-test1) for executables and [another](https://github.com/szaghi/FoBiS/tree/master/src/unittest/python/install-test2) for libraries.

The new `install` command works essentially as you indicated, but with some differences:

+ the prefix specification must be *comprehensive*, namely FoBiS does not add `bin` or `lib` sub-path automatically; this can be changed easily in the future, but for the moment I prefer to adopt a minimal footprint *a priori* assumptions (I am not sure that `bin` or `lib` are always adopted);
+ for the installation of libraries I currently copy only the (possible) module associated to the `target` source file: for building a library with FoBiS you always must specify a target source, thus it comes very natural to copy its module file in the case it is a module; in the future adding options to copy others modules or excluding other ones should be very easy;
+ I do not change the *compiling heritage* mechanism, rather I added a new hidden file category: `*.track_build* files are created (into the build directory) for each built object (for all targets either automatic targets or user specified); into each `*.track_build` file there are the infos necessary for the subsequent installation.

Due to my choice on how *track* buildings, you have to respect the order

```shell
FoBiS.py build
FoBiS.py install --prefix path_of_your_choice
```

If you try to install without a *build structure* you obtain the following error:

```shell
→ FoBiS.py install -p there
Error: build directory not found! Maybe you have to run "FoBiS.py build" before.
```

Before making this master branch a new release I would like to have to your feedback about all the modifications I made today.

Cheers

**Comment by cmacmackin** [comment]
Thanks for this work. I'm not clear, though, on how both libraries and module files can be install with one command if you have to include the `/lib` in the prefix. Module files should go into a directory called `/include` which is on the same level as `/lib`.

I hate to add more work, but something else which might actually work better would be to specify a flag for build jobs which adds their output to an install list. Then, the install command installs everything on that list. However, to be effective, this may require a non-backwards compatible change. Currently, the object directory and the module directory are subdirectories of the output directory for the libraries or executables. It would be better if these could all be set independently. That way, commands like
```
FoBiS.py build -mode static-lib
FoBiS.py build -mode shared-lib
FoBiS.py build -mode executable
```
would produce something like the following.
```
project
├── build
│   ├── bin
│   │   └── fortran_executable
│   ├── include
│   │   ├── library_mod.mod
│   │   └── library_other_mod.mod
│   └── lib
│       ├── executable_lib.a
│       └── executable_lib.so
├── fobos
├── obj
│   ├── fortran_executable.o
│   ├── library.o
│   ├── library_other.o
│   └── utilities.o
└── src
    ├── fortran_executable.f90
    ├── library.f90
    ├── library_other.f90
    └── utilities.f90
```
The contents of the build directory could be fairly easily transferred to a Unix-organised file system.

I get that I'm asking for some fairly big changes to FoBiS's way of working, so feel free to ignore my requests.

**Comment by szaghi** [comment]
@cmacmackin 

Do not worry.

I'll think to this later today. Anyhow, I have just one preliminary comment: if your main complain is that .mod files should go into include sub-directory, this can be easily done without modify the build phase rather this is a little improvement for the install one. As I said, install has now a minimal footprint implementation, but I should have done it with enough flexibility to add new features, e.g. putting .mod into different place. Let me think to it.

**Comment by szaghi** [comment]
@cmacmackin 

Chris, in the just uploaded new master branch there is the requested improvement. Now your scenario is:

```shell
FoBiS.py build --track_build # build and track building, enable with also abbreviated switch -tb or by "track_build = True" into fobos
FoBiS.py install --prefix my_path # will install the previous built objects into my_path
tree my_path
└── bin
    └── hello
# or for library
tree my_path
├── include
│   └── library.mod
└── lib
    └── liblibrary.so
```

The sub-directories of prefix, `bin`, `lib` and `include` can be customized during the install command:

```shell
→ FoBiS.py install -h
usage: FoBiS.py install [-h] [-dbld BUILD_DIR] [-p PREFIX] [--bin BIN]
                        [--lib LIB] [--include INCLUDE] [-f FOBOS] [-fci]
                        [-mode MODE] [-lmodes] [--print_fobos_template]
                        [-force_compile] [-colors] [-l] [-graph] [-q]
                        [-verbose] [-j JOBS] [-m MAKEFILE_name]

optional arguments:
  -h, --help            show this help message and exit

directories:
  -dbld BUILD_DIR, --build_dir BUILD_DIR
                        Directory containing built objects [default: ./]
  -p PREFIX, --prefix PREFIX
                        Prefix path where built objects are installed
  --bin BIN             Prefix sub-directory where executable files are
                        installed
  --lib LIB             Prefix sub-directory where library files are installed
  --include INCLUDE     Prefix sub-directory where include files are installed
...
```

I preferred to no modify the build command: build-structure can be a very personal taste, whereas install-structure is surely more *standardized*.

Let me know what you think about.

Cheers

**Comment by cmacmackin** [comment]
Great, that should work!

**Comment by szaghi** [comment]
Coming in the next release

**Comment by cmacmackin** [comment]
Just a heads-up: I see that the install feature is not documented in the wiki. You may want to add some information there at some point.

**Comment by cmacmackin** [comment]
Come across another issue: the install feature assumes that all modules have the same name as the source file containing them. As such, it can end up trying to copy mod files which don't exist. Seeing as you parse the files to get the interdependencies hopefully it won't be too hard to teach the install feature what the appropriate module names are for each file.

**Comment by cmacmackin** [comment]
Oh, and one last request. Could you make sure that when files are copied from the build directory to the install locations, all symlinks are preserved? Often people will have a shared object with the full version number at the end and then have a symlink to it with a name not including the version number. For example:

```
$ ls -l /usr/lib/libblas.so*
lrwxrwxrwx 1 root root   16 Jan 16  2016 /usr/lib/libblas.so -> libblas.so.3.6.0
lrwxrwxrwx 1 root root   16 Sep 11 19:12 /usr/lib/libblas.so.3 -> libblas.so.3.6.0
-rw-r--r-- 1 root root 444K Jan 16  2016 /usr/lib/libblas.so.3.6.0
```

**Comment by cmacmackin** [comment]
Sorry, just clued in that since FoBiS doesn't produce those sorts of symlinks, it doesn't make sense to have it able to copy them. The option to create symlinks to the output would be useful, though; flags like `--symlink libblas.so --symlink libblas.so.3 -o libblas.so.3.6.0` to create the link-structure I showed above. Note that these would need to be relative symlinks and that, as explained above, the install command would need to preserve the fact that they are symlinks when it does the copying.
