### ISSUE TITLE
Building shared libraries

### ISSUE THREAD

**Issue by cmacmackin** [szaghi/FoBiS#88]
Hi Stefano. I've come across what appears to be a bug in the building of shared libraries. FoBiS.py is not automatically using the `-shared` flag in the link command. If this is included manually in the link flags specified by the user then it will still work fine. However, this should not be necessary. It also creates problems with the templates used in some fobos files, such as those in FACE, where the same flags are used for both shared and static libraries.

**Comment by szaghi** [comment]
@cmacmackin 

Dear Chris, 

I should have fixed this in the just uploaded master branch. Now, if `mklib=shared` is used (in CLI or in fobos) automatically the linking flags are checked for presence of `-shared` and in case it is added. I am not sure that all *mainstream* compilers use `-shared`: Intel and GNU use the same switch name... so also `g95` and `opencoarrays-gnu`. I have to check IBM and others (that, however, are not supported yet).

I added a new test, build-test25: it has mklib= shared, but not explicitly defined `-shared` flag.

Let me know if it is ok for you.

**Comment by cmacmackin** [comment]
To complicate things a bit, I gather that `ifort` uses a different flag when compiling on Mac. I'd guess it's different again on Windows. But I suspect that handling that is beyond the scope of FoBiS.py. I don't know what the commands are for any of the other compilers, but until they are integrated into FoBiS it's irrelevant. If they are different then presumably you can just add a new variable to keep track of what flag to use.

**Comment by cmacmackin** [comment]
A related issue with building shared libraries is that you should really include dependencies in the link stage, just as you would when building an executable (see [this article](http://www.kaizou.org/2015/01/linux-libraries.html)). At present FoBiS does not do this, but I'd think it should be trivial to implement.

**Comment by cmacmackin** [comment]
Oh, one more thought: the directives to link these libraries would have to go after all of the object files, in order for the linker to actually be able to find the routines it needs. This is just the same as when producing an executable.

**Comment by szaghi** [comment]
@cmacmackin 

Chris, I read the article very quickly (preparing the breakfast for my family...) thus I have not *captured* all details (I'll study deeply later today), but for linking a shared library currently FoBiS pass *many* things... see this

https://github.com/szaghi/FoBiS/blob/master/src/main/python/fobis/Builder.py#L416

+ all the compiled objects (.o) necessary for building the library itself;
+ all the libraries the user specified as dependency;

I am not sure about the so called *secondary dependency* means in the article. Anyhow, I booked the article and I'll study it later. Thank you very much for the insight!

> Oh, one more thought: the directives to link these libraries would have to go after all of the object files, in order for the linker to actually be able to find the routines it needs. This is just the same as when producing an executable.

Can you give me an example?

Cheer

**Comment by cmacmackin** [comment]
I looked at the code and the problem is that you only link in the internal libraries. You don't link those in the `ext_libs` and `ext_vlibs` variables. The place you've included the internal libraries in the link command is after all object files, so as long as external libraries go after this then everything will work.

To explain the concept of secondary dependencies, let's say you have two libraries: `libalpha.so` and `libbeta.so`. The first of these depends on the second. Now say that you are writing a program which calls routines in `libalpha.so`, but does not (directly) call any routines in `libbeta.so`. (A real-world example of this would be programs calling LAPACK, which depends on BLAS.) Ideally, when linking your program, the only library you'd want to include in the link command is `libalpha.so`, as it is the only _direct_ dependency. However, the executable will still need to have `libbeta.so` available and it is a _secondary dependency_. 

The way that this can be achieved is to include `-lbeta` when linking the shared-object for `libalpha.so`. Then the only library which will need to be included when linking the program is `-lalpha`. Depending on where the libraries are located, it may be necessary to have some extra command specifying directories in which to look for them, but that's beyond the scope of this discussion.

**Comment by szaghi** [comment]
@cmacmackin 

Chris, thanks for pointing this issue out. I have amend the *link phase*: now *all* is passed, also user-provided external libraries. However, I have not done a tailed test with *secondary library* dependency, it is somehow tricky to setup such a test on Travis. If in the future you (or other) find an issue related with secondary dependencies I'll try to fix it.

The new release 2.2.0 is now also on PyPi.

Thank a lot, I wish you enjoy a happy Christmas with your family.

Cheers
