### ISSUE TITLE
Space inserted when using variable for output name

### ISSUE THREAD

**Issue by cmacmackin** [szaghi/FoBiS#91]
I found that when I use a variable to store the name of the output in a fobos file, a space gets inserted between the output directory and the variable contents. This makes it seem like these are separate arguments to the compiler and leads to an error. For example, a fobos file like:

```ini
[common-variables]
$STATIC_LIB = libstatic.a

[static-lib]
compiler = gnu
mklib = static
target = file.f90
build_dir = ./build
output = $STATIC_LIB
```
will result in the following archive command being run:
```
ar -rcs build/ libstatic.a  build/obj/file.o
```

**Comment by szaghi** [comment]
@cmacmackin 

Great! Got it, I'll fix today, new release is coming.

**Comment by szaghi** [comment]
@cmacmackin 

Dear Chris, in the just uploaded master branch I should have fixed this bug.

I added also a specific test [this one](https://github.com/szaghi/FoBiS/tree/master/src/unittest/python/build-test23).

Soon, I'll create a new release with the other features.

I leave this open until your check on the new release.

**Comment by cmacmackin** [comment]
Great, thanks.

**Comment by szaghi** [comment]
Should be fixed, feel free to reopen if not.
