### ISSUE TITLE
Excluding multiple files and directories

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#98]
I would like to specify in a fobis file that certain directories be excluded. The `exclude` statement isn't working (maybe that is only for individual files?) Perhaps add an `exclude_dir` option for directories, or allow for the `exclude` to work with directories like so:
```
exclude = ./src/third-party-lib/src/tests/
```
And/or, you could allow wildcards to specify multiple files:
```
exclude = ./src/third-party-lib/src/tests/*.f90
```

**Comment by giacombum** [comment]
Hi @jacobwilliams, there's already an option for excluding whole directories, see [here](https://github.com/Fortran-FOSS-Programmers/WenOOF/blob/master/fobos#L16).

**Comment by jacobwilliams** [comment]
Thanks! I completely missed that one!
