### ISSUE TITLE
Some Intel/ifort flags deprecated

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FoBiS#99]
FoBiS.py passes `openmp` when `-compiler intel` but the Intel `ifort` manpage says that:

> Option -qopenmp is the replacement option for -openmp, which is deprecated.

I'm guessing there are probably some more flags that need a `q` prepended to them as well.

**Comment by szaghi** [comment]
Dear @zbeekman ,

happy to read you again.

You are right, I'll fix ASAP, but this is a very bad period for me, I am sorry.

Cheers.

**Comment by zbeekman** [comment]
No worries, I'll submit a PR if I get to it before you do.

**Comment by szaghi** [comment]
Dear @zbeekman 

I am very sorry for my delay, I should have fixed this with the new 3.0.1 that should be also compatible with python 3 (tested on a python 3.8 env).

Feel free to reopen this if it is not well fixed.
